version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - nats
    ports:
      - 8080:${SERVER_PORT}

  postgres:
    image: postgres:16-alpine3.18
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD:${DB_PASSWORD}
      - POSTGRES_USER:${DB_USER}
      - POSGRES_DB:${DB_NAME}
    ports:
      - 5432:${DB_PORT}
    healthcheck:
      test: ["CMD", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  nats:
    image: nats-streaming
    command: -js -sd /data
    depends_on:
      - postgres
    volumes:
      - nats:/data
    ports:
      - 4222:4222
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres:
  nats: